### ISSUE TITLE
Fix pre-existing spdlog/fmt/fmt.h include error in logger.hpp

### ISSUE THREAD

**Issue by mvillmow** [HomericIntelligence/ProjectKeystone#177]
During implementation of issue #86, the existing `unit_tests` build target was found to be broken with:

  include/concurrency/logger.hpp:7:10: fatal error: spdlog/fmt/fmt.h: No such file or directory

This failure predates this branch (confirmed by stashing changes and observing the same error). The include path `spdlog/fmt/fmt.h` is incorrect when spdlog is built with an external fmt; the correct include when `SPDLOG_FMT_EXTERNAL` is defined is `<fmt/format.h>` (or simply rely on spdlog's own includes). This blocks the main `unit_tests` suite from building under the Conan 2 toolchain introduced in commit 220326c.

_Follow-up from #86_

**Comment by mvillmow** [comment]
Duplicate of #173 — same root cause: spdlog/fmt/fmt.h include path not propagated via Conan toolchain.
